version: '3.8'

services:
  spark-job:
    image: bitnami/spark:latest
    volumes:
      - /home/abderrahmane/Desktop/bigdata/server:/app
    entrypoint: /bin/bash -c "
      apt-get update && \
      apt-get install -y python3-pip cron && \
      pip install pytz && \
      echo '0 * * * * /opt/bitnami/spark/bin/spark-submit /app/spark.py >> /var/log/cron.log 2>&1' > /etc/cron.d/spark-cron && \
      chmod 0644 /etc/cron.d/spark-cron && \
      crontab /etc/cron.d/spark-cron && \
      cron && tail -f /var/log/cron.log"
    restart: unless-stopped
